import { expect } from 'chai';
import { buildOutfileName, runClocSummary } from './cloc.functions';

// #copilot - most of the boilerplate of these tests was generated by copilot
describe('runCloc', () => {
    it('should return an array of language statistics', (done) => {
        runClocSummary('./src').subscribe((stats) => {
            expect(stats instanceof Array).to.be.true;
            expect(stats.length).greaterThan(0);
            expect(!!stats[0].language).to.be.true;
            expect(!!stats[0].nFiles).to.be.true;
            expect(!!stats[0].blank).to.be.true;
            expect(!!stats[0].comment).to.be.true;
            expect(!!stats[0].code).to.be.true;
            done();
        });
    }).timeout(10000);

    it('should return statistics for TypeScript files', (done) => {
        runClocSummary('./src').subscribe((stats) => {
            const typescriptStats = stats.find((stat) => stat.language === 'TypeScript');
            expect(!!typescriptStats).to.be.true;
            expect(typescriptStats!.nFiles).greaterThan(0);
            expect(typescriptStats!.blank).greaterThan(0);
            expect(typescriptStats!.comment).greaterThan(0);
            expect(typescriptStats!.code).greaterThan(0);
            done();
        });
    }).timeout(10000);

    it('should return statistics reading from a git repo commit - the commit is from the repo of this project', (done) => {
        runClocSummary('2c6f2ae87b539590f5a0f93682f5440ca845bc9c').subscribe((stats) => {
            const typescriptStats = stats.find((stat) => stat.language === 'TypeScript');
            expect(!!typescriptStats).to.be.true;
            expect(typescriptStats!.nFiles).greaterThan(0);
            expect(typescriptStats!.blank).greaterThan(0);
            expect(typescriptStats!.comment).greaterThan(0);
            expect(typescriptStats!.code).greaterThan(0);
            done();
        });
    }).timeout(10000);
});

describe('buildOutfileName', () => {

    const thisFolderName = 'git-metrics';

    it('should return the provided output file name if it is provided', () => {
        const outFile = 'output.txt';
        const result = buildOutfileName(outFile);
        expect(result).to.equal(outFile);
    });

    it('should generate an output file name based on the provided parameters', () => {
        const prefix = 'prefix_';
        const repoFolder = '/path/to/repo';
        const postfix = '_postfix';
        const expected = `${prefix}repo${postfix}`;
        const result = buildOutfileName('', repoFolder, prefix, postfix);
        expect(result).to.equal(expected);
    });

    it('should use the current working directory name as the base folder name since repo folder is not passed as param', () => {
        const prefix = 'prefix_';
        const postfix = '_postfix';
        const expected = `${prefix}${thisFolderName}${postfix}`;
        const result = buildOutfileName('', '', prefix, postfix);
        expect(result).to.equal(expected);
    });

    it('should use an empty string as the prefix if prefix is not provided', () => {
        const repoFolder = '/path/to/repo';
        const postfix = '_postfix';
        const expected = `repo${postfix}`;
        const result = buildOutfileName('', repoFolder, undefined, postfix);
        expect(result).to.equal(expected);
    });

    it('should use an empty string as the postfix if postfix is not provided', () => {
        const prefix = 'prefix_';
        const repoFolder = '/path/to/repo';
        const expected = `${prefix}repo`;
        const result = buildOutfileName('', repoFolder, prefix, undefined);
        expect(result).to.equal(expected);
    });

    it('should use the current working directory name as the base folder name if repoFolder is "."', () => {
        const prefix = 'prefix_';
        const postfix = '_postfix';
        const expected = `${prefix}${thisFolderName}${postfix}`;
        const result = buildOutfileName('', '.', prefix, postfix);
        expect(result).to.equal(expected);
    });

    it('should use the current working directory name as the base folder name if repoFolder is "."', () => {
        const prefix = 'prefix_';
        const postfix = '_postfix';
        const expected = `${prefix}${thisFolderName}${postfix}`;
        const result = buildOutfileName('', './', prefix, postfix);
        expect(result).to.equal(expected);
    });

    it('should use the current working directory name as the base folder name if repoFolder is an empty string', () => {
        const prefix = 'prefix_';
        const postfix = '_postfix';
        const expected = `${prefix}${thisFolderName}${postfix}`;
        const result = buildOutfileName('', '', prefix, postfix);
        expect(result).to.equal(expected);
    });
});