// ClocLanguageStats is an interface that represents the statistics about a language
// produced by the cloc tool
// #copilot - the following interface was generated by copilot
export interface ClocLanguageStats extends ClocStats {
    language: string;
}

export interface ClocStats {
    nFiles: number;
    blank: number;
    comment: number;
    code: number;
}
